//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrapping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public BaiViet()
        {
            this.RatePosts = new HashSet<RatePost>();
        }
    
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string NguoiDang { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public int Trangthai { get; set; }
        public string Tabs { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<RatePost> RatePosts { get; set; }
    }
}
