//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrapping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diem247Entities : DbContext
    {
        public diem247Entities()
            : base("name=diem247Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SystemLogs> SystemLogs { get; set; }
        public virtual DbSet<TempTruong> TempTruong { get; set; }
        public virtual DbSet<truongnganhmonthi> truongnganhmonthi { get; set; }
    }
}
