//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrapping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectHEntities : DbContext
    {
        public ProjectHEntities()
            : base("name=ProjectHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BaiViets> BaiViets { get; set; }
        public virtual DbSet<InternalMessage> InternalMessage { get; set; }
        public virtual DbSet<KhoiThis> KhoiThis { get; set; }
        public virtual DbSet<MBTI> MBTI { get; set; }
        public virtual DbSet<Nganhs> Nganhs { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<RatePost> RatePost { get; set; }
        public virtual DbSet<Sach> Sach { get; set; }
        public virtual DbSet<SachChoMuon> SachChoMuon { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemInformation> SystemInformation { get; set; }
        public virtual DbSet<SystemLogs> SystemLogs { get; set; }
        public virtual DbSet<ThanhPhoes> ThanhPhoes { get; set; }
        public virtual DbSet<TruongNganhMonthis> TruongNganhMonthis { get; set; }
        public virtual DbSet<Truongs> Truongs { get; set; }
        public virtual DbSet<UserComments> UserComments { get; set; }
        public virtual DbSet<TruongNganhs> TruongNganhs { get; set; }
    }
}
