//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrapping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nganh
    {
        public Nganh()
        {
            this.TruongNganhs = new HashSet<TruongNganh>();
        }
    
        public string Ten { get; set; }
        public string MaNganh { get; set; }
    
        public virtual ICollection<TruongNganh> TruongNganhs { get; set; }
    }
}
