//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrapping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truongs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truongs()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.TruongNganhMonthis = new HashSet<TruongNganhMonthis>();
            this.TruongNganhs = new HashSet<TruongNganhs>();
        }
    
        public string Ten { get; set; }
        public string Website { get; set; }
        public int IDThanhPho { get; set; }
        public string MaTruong { get; set; }
        public string LoaiTruong { get; set; }
        public string linkLogo { get; set; }
        public string DeAnTuyenSInh { get; set; }
        public string GioiThieu { get; set; }
        public string background { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        public virtual ThanhPhoes ThanhPhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruongNganhMonthis> TruongNganhMonthis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruongNganhs> TruongNganhs { get; set; }
    }
}
