//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrapping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class truongnganhmonthi
    {
        public string matruong { get; set; }
        public string manganh { get; set; }
        public string ToHopMon { get; set; }
        public string tennganh { get; set; }
        public string tentruong { get; set; }
        public Nullable<double> diem { get; set; }
    }
}
